### ISSUE TITLE
Refactor basename to not double work

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/faster_path#130]
The edge case in the basename method is causing the method to take twice as long.  This line:

```rust
// Known edge case
if &pth.squeeze("/")[..] == "/" { return "/".to_string(); }
```

Is repeating the work over the string a second time and should be refactored in with the existing method (possibly just for this one case)… as-in we'll only perform a squeeze on the slashes of path in this method and not others.

**Comment by glebm** [comment]
The `squeeze` thing must be super-slow. I wonder if checking that all bytes equal `MAIN_SEPARATOR as u8` would be *much* faster:

```rust
pth.as_bytes().all(|b| b == SEP)
```

**Comment by danielpclark** [comment]
@glebm On this issue I think the `pub fn extract_last_path_segment(path: &str) -> &str;` method should be copied into this method and rewritten to automatically produce the squeezed result.  That way we don't process the string more than once.

**Comment by danielpclark** [comment]
Closing for now.  Me revisit this issue if the need arises.
