### ISSUE TITLE
OS X install failed

### ISSUE THREAD

**Issue by trooster** [danielpclark/faster_path#144]
Compiling/installing the faster_path gem on os x failed:

`error[E0554]: #![feature] may not be used on the stable release channel
 --> src/lib.rs:7:1
  |
7 | #![feature(try_from)]
  | ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `faster_path`.
`

I also tried installing the beta version of rust via:
`curl https://sh.rustup.rs -sSf | sh`

But that gave the same error

**Comment by danielpclark** [comment]
It requires Rust nightly.  Did you manually try to install it or was it part of the install process built in with Thermite?

**Comment by danielpclark** [comment]
I'm importing the trait `TryFrom` locally now so you won't need nightly Rust.
