### ISSUE TITLE
Version 0.0.7 doesn't install

### ISSUE THREAD

**Issue by sinankeskin** [danielpclark/faster_path#15]
I said you don't need Makefile before but obviously you do. Error occured and gem didn't install.
It says Makefile not found.

![ss](https://cloud.githubusercontent.com/assets/2091777/16005090/04fbee34-316e-11e6-91ed-ac20ecc2aa79.png)

I think you should add your ``create_makefile('faster_path/dummy')`` again. Sorry.

**Comment by danielpclark** [comment]
Done.  It's been yanked.
