### ISSUE TITLE
Add long running performance benchmark feature

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/faster_path#154]
Travis CI benchmarks seem to be very volatile and we really could use something more accurate for permanent record.  I'm suggesting adding a `--long-run` flag to the PBench (Pinch Bench) suite to run much longer and have that used only on Travis CI master branch merges.

We will of course need to make sure that it won't time out on Travis CI if there are any time limitations (of which I'm not sure).

Thinking more about this I believe I should also have it work with an environment flag and only have one CI runner perform this action under allowed failures.  It should be a Linux only system as that will allow other PRs to start there tests even if it's still running.

**Comment by glebm** [comment]
The long run numbers here are very close to what I get on my machine!

https://travis-ci.org/danielpclark/faster_path/jobs/353433323

**Comment by danielpclark** [comment]
I updated the README with the new numbers
