### ISSUE TITLE
Implement Pathname#join

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/faster_path#22]
Rust seems to have it's own path joining methods. http://rustbyexample.com/std_misc/path.html  This "may" do exactly what we want.
- [ ] Write Rust implementation of `Pathname#join` to `FasterPath.join`
- [ ] Write refinements and monkey-patches for `Pathname#join` and map implementation to `Pathname.new(result)`
- [ ] Write tests proving `FasterPath.join` operates the same as `Pathname#join` 
- [ ] Write benchmarks in `test/benches` and compare the performance.
- [ ] Copy benchmarks to `test/pbench/pbench_suite.rb`

**Comment by mrageh** [comment]
@danielpclark I'd like to attempt adding `FaterPath.join`

**Comment by danielpclark** [comment]
Have at it :-)
