### ISSUE TITLE
Replace use of include! with modules

### ISSUE THREAD

**Issue by jdm** [danielpclark/faster_path#37]
Instead of including each file's contents inside `lib.rs` using `include!`, it is more idiomatic to use Rust's modules instead. That would look like:
```rust
pub use a::some_function;
pub use b::some_other_function;

mod a;
mod b;
```
rather than
```rust
include!("a.rs")
include!("b.rs")
```

**Comment by steveklabnik** [comment]
Big :+1: . I also believe that you won't get incremental compilation with this approach, but modules will let you.

**Comment by danielpclark** [comment]
Did not know that @steveklabnik .  I used includeds because it was the least hastle to get going.  But if some one would be willing to reformat it into modules I'd be willing to go that way. :+1:

**Comment by steveklabnik** [comment]
To be clear, we don't have incremental recompilation _yet_, but when we do, this will matter :smile:
