### ISSUE TITLE
Implement Pathname#plus

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/faster_path#4]
This is a rather long method and highly used one.  It would be great to have a Rust implementation of it.  Here's the current Ruby source:

```
def plus(path1, path2) # -> path # :nodoc:
  prefix2 = path2
  index_list2 = []
  basename_list2 = []
  while r2 = chop_basename(prefix2)
    prefix2, basename2 = r2
    index_list2.unshift prefix2.length
    basename_list2.unshift basename2
  end
  return path2 if prefix2 != ''
  prefix1 = path1
  while true
    while !basename_list2.empty? && basename_list2.first == '.'
      index_list2.shift
      basename_list2.shift
    end
    break unless r1 = chop_basename(prefix1)
    prefix1, basename1 = r1
   next if basename1 == '.'
    if basename1 == '..' || basename_list2.empty? || basename_list2.first != '..'
      prefix1 = prefix1 + basename1
      break
   end
    index_list2.shift
    basename_list2.shift
  end
  r1 = chop_basename(prefix1)
  if !r1 && /#{SEPARATOR_PAT}/o =~ File.basename(prefix1)
    while !basename_list2.empty? && basename_list2.first == '..'
      index_list2.shift
      basename_list2.shift
    end
  end
  if !basename_list2.empty?
    suffix2 = path2[index_list2.first..-1]
    r1 ? File.join(prefix1, suffix2) : prefix1 + suffix2
  else
    r1 ? prefix1 : File.dirname(prefix1)
  end
end
private :plus
```

At the moment I'm not using regex in the library so it would be great if we could implement `if !r1 && /#{SEPARATOR_PAT}/o =~ File.basename(prefix1)` with something like `str.contains(MAIN_SEPARATOR)`.

Better yet if you look into Rust's path implementation you may find something that does all of this for you.  We'll need to have tests to confirm the same behavior is achieved.

**Comment by julienXX** [comment]
Can I try this one?

**Comment by danielpclark** [comment]
Yes.  Have at it. :-)

**Comment by danielpclark** [comment]
Did you get a chance to work on this?

**Comment by julienXX** [comment]
Yes it's in progress with great results so far. Will open a PR soon.

**Comment by danielpclark** [comment]
I've added a new benchmark system called pbench.  You can run `rake pbench` to see how much the method performance has improved.  You will need to have benchmark code added to `test/pbench/suite.rb` to see it.  This is brand new on the master branch.
