### ISSUE TITLE
Audit usage of CString::into_raw

### ISSUE THREAD

**Issue by Ryman** [danielpclark/faster_path#41]
To quote the docs:

> The pointer must be returned to Rust and reconstituted using from_raw to be properly deallocated. Specifically, one should not use the standard C free function to deallocate this string.
> 
> Failure to call from_raw will lead to a memory leak.

Something similar to [`rb_str_new_cstr`](https://github.com/d-unseductable/ruru/blob/master/src/binding/string.rs) should probably be used.

**Comment by danielpclark** [comment]
I could use more information on this.  How would I audit this, or how would `rb_str_new_cstr` be implemented here?

**Comment by Ryman** [comment]
The issue is that we're allocating within Rust and passing the ownership to Ruby who is either going to not free it (memory leak) or may call an incorrect `free` function (not sure what happens in that case but its undesirable). 

There's a [thread on the ffi library's repo about this](https://github.com/ffi/ffi/issues/467#issuecomment-159199546) and a better example on [their wiki about fresh memory](https://github.com/ffi/ffi/wiki/Pointers#fresh-memory).

If I understand the [ffi docs](https://github.com/ffi/ffi/wiki/Types#types) correctly, I think `:string` should only be used to return a ptr to an already allocated, and owned by the Ruby GC, `String` object. I don't really find the documentation too clear on that point though. The`strptr` type looks more correct to use if you want to continue to return CStrings (you can find mention of it on the fresh memory link above) and have them freed through Rust.

I'm not exactly sure how you might change to use `rb_str_new_cstr`, perhaps you can allocate it with that function and then return that as a pointer? 

I'm mainly logging this issue so that someone with more Ruby ffi knowledge here might be able to make a clear call about this. cc @steveklabnik @d-unseductable

**Comment by danielpclark** [comment]
Proper example to free pointer via FFI is available here: http://jakegoulding.com/rust-ffi-omnibus/string_return/

**Comment by danielpclark** [comment]
> Something similar to rb_str_new_cstr should probably be used.

Ruby's own methods are now used as I've converted this project over to ruru #122
