### ISSUE TITLE
Function 'basename' not found error.

### ISSUE THREAD

**Issue by sinankeskin** [danielpclark/faster_path#44]
On Windows ``Function 'basename' not found`` error happening. I tried on Linux everything looks ok.

``Windows 7 x64``
``Ruby 2.3.1 x64 mingw``
``faster_path 0.1.5``

Screenshot:
![ss](https://cloud.githubusercontent.com/assets/2091777/16164301/0206d380-34e6-11e6-95e0-89b19ba66913.png)

**Comment by mble** [comment]
@danielpclark `#[no_mangle]` is commented out for `basename`, was done so in 6c2e149e. What was the rationale here?

**Comment by danielpclark** [comment]
It shouldn't be commented out.  Previously the whole method block was commented out during testing.  It just happened to not get uncommented once the method was returned.  It's a mistake.

Do you know if there are tests in Rust we can use to verify certain methods still have `#[no mangle]`?

I'll be more careful about this.

**Comment by mble** [comment]
> Do you know if there are tests in Rust we can use to verify certain methods still have `#[no mangle]`

This could probably be done by writing a compiler plugin and having an arbitrary [lint check attribute for it](https://doc.rust-lang.org/reference.html#lint-check-attributes)

Alternatively, could write a script to parse the Rust source by line before compiling and check that that the FFI functions have `#[no_mangle]` above them (uncommented).
