### ISSUE TITLE
rubocop, rustfmt and clippy runs

### ISSUE THREAD

**Issue by mble** [danielpclark/faster_path#46]
The excellent https://github.com/rust-lang-nursery/rustfmt and https://github.com/Manishearth/rust-clippy could be run to unify style and provide some feedback about pattern usage in the Rust section of the repository.

This would potentially make the project more attractive to Rustaceans, and provides a similar comfort to Rubyists who are familiar with Rubocop.

**Comment by danielpclark** [comment]
I've looked into these a little bit.  The first one looks like a stand alone command tool.  So the only thing I might be able to do is include some flags around methods like `#[lint(thing]` ... but I have a concern then that other people won't be able to work without it then.

**Comment by mble** [comment]
`rubocop` can just be a one off thing, or it can run as part of a test suite - if any of the Ruby violates any of the cops, it's a failure. I can open a PR for this.

`rustfmt` should be used prior to patch. No need to force it on people, but would help unify the style a bit.

`clippy` is an odd case as it is more of a guide, but [the list of lints](https://github.com/Manishearth/rust-clippy/wiki) is very useful as a sort of 'good Rust style' guide.

**Comment by danielpclark** [comment]
I've incorporated Rubocop.  It is a good idea to create some sort of quality standard for users to contribute.
