### ISSUE TITLE
Pathname#has_trailing_separator?

### ISSUE THREAD

**Issue by mble** [danielpclark/faster_path#49]
I'd like to take on `Pathname#has_trailing_separator?`, as outlined in https://github.com/danielpclark/faster_path/issues/30

<hr>

- [x] Write Rust implementation of `Pathname#has_trailing_separator?` to `FasterPath.has_trailing_separator?`
- [x] Write refinements and monkey-patches for `Pathname#has_trailing_separator?` and map implementation to `FasterPath.has_trailing_separator?`
- [x] Write tests from existing sources proving `FasterPath.has_trailing_separator?` operates the same as `Pathname#has_trailing_separator?`
- [x] Write benchmarks in test/benches and compare the performance.
- [x] Also compare both the original to the new method to verify compatibility.

**Comment by danielpclark** [comment]
Thanks.  I'll be getting to this soon!  Not ignoring it! :+1:
