### ISSUE TITLE
Save 75% performance by not raising TypeError

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/faster_path#64]
So with the recent regression I did some digging and `nil` checking is costly.

I found a way to get 75% performance speed with `FasterPath.basename` but it requires that we not use the behavior of raising `TypeError` with `nil`.

The method will look a little quirky.  The adding of this `unless` check saves 75% of the time that the C `File.basename` implementation takes.

```ruby
module FasterPath
  def self.basename(pth, ext="")
    Rust.basename(pth, ext) unless (pth || ext) 
  end
end
```

versus the 6 times slower implementation

```ruby
module FasterPath
  def self.basename(pth, ext="")
    unless (pth || ext) 
      return Rust.basename(pth, ext) 
    end
    raise TypeError, "no implicit conversion of nil into String"
  end
end
```
The difference in behavior would be

```ruby
assert_raises(TypeError){File.basename(nil, nil)} 
assert_nil FasterPath.basename(nil,nil)

assert_raises(TypeError){File.basename(nil, '')} 
assert_nil FasterPath.basename(nil,'')

assert_raises(TypeError){File.basename('', nil)} 
assert_nil FasterPath.basename('',nil)
```

Personally I'm fine with this as it simply defers the responsibility of nil and may be useful in checks as people would have to call `rescue` anyways.  Ruby 2.3 even introduces the lonely operator `&.` which in essence does just that.

The question becomes how strongly are we going to conform to not breaking anything verses what may be quite reasonably considered moving forward?  Also I don't think we've implemented `TypeError` on most items.  We didn't have to worry about it with `Pathname` because the initialize method handled it for us.

**A better idea** might be to map newer `File` methods all to `Pathname` so **we add the guarantee of not breaking anything** by getting its built-in type checking _as a bonus_ and the methods themselves can have higher gains.

Also people can always make pure calls to `FasterPath.basename` itself and get the full speed savings.

cc @glebm - what do you think?

**Comment by danielpclark** [comment]
cc @glebm

**Comment by danielpclark** [comment]
None of this would be a breaking change for this gem as we haven't raised `TypeError` for anything as of yet.

**Comment by glebm** [comment]
Perhaps we can implement 100% Ruby-compatible API without speed loss if we raise errors directly from Rust using `rb_raise`.

**Comment by danielpclark** [comment]
Maybe I should sleep before making decisions like this.  I don't know why the basename tests are passing.  All it does now is return `nil`.

*facepalm*

**Comment by danielpclark** [comment]
I'm yanking 0.1.9 and reverting... I'll look at this another time.

**Comment by glebm** [comment]
Sleep well dude :smile:
