### ISSUE TITLE
Could not open library 'faster_path.so'

### ISSUE THREAD

**Issue by Frexuz** [danielpclark/faster_path#68]
Using capistrano to deploy:

```
 * executing "cd /var/www/example.com/production/releases/20160620172947 && bundle exec rake RAILS_ENV=production RAILS_GROUPS=assets assets:precompile"
    servers: ["example.com"]
    [example.com:242] executing command
 ** [out :: example.com:242] rake aborted!
 ** [out :: example.com:242] LoadError: Could not open library '/var/www/example.com/production/shared/bundle/ruby/2.3.0/gems/faster_path-0.1.8/target/release/libfaster_path.so': /var/www/example.com/production/shared/bundle/ruby/2.3.0/gems/faster_path-0.1.8/target/release/libfaster_path.so: cannot open shared object file: No such file or directory
```
- I don't seem to have a `target/release/lib` folder under `faster_path-0.1.8/`
- There seems to be a missing `/` between `lib` and `faster_path.so`?

**Comment by danielpclark** [comment]
@Frexuz, no the file name has `lib` in front of it on Linux distros.  Your issue is related to #18 and #20 .  The cargo build command isn't getting run during installation on mostly Macs but occasionally some other distros.  The most likely theory now is that some distros donit bundle cargo with Rust.

**Comment by Frexuz** [comment]
I'm on Ubuntu 14.04. And cargo is installed.
cargo -V `cargo 0.10.0-nightly (10ddd7d 2016-04-08)`

Is the cargo build command supposed to run on every 'bundle install' ?

**Comment by danielpclark** [comment]
Yes.

**Comment by epitron** [comment]
Related issue: I had rust installed, but not cargo, and `gem install faster_path` appeared to install with no error, but would be unable to find the `.so` file when I requried it.

Right now, `rake build_lib` appears to work when you run it without `cargo` or `rust`. It would be nice if it displayed an error, and aborted the gem install process.

**Comment by danielpclark** [comment]
@epitron Bundler is swallowing up the current error messages.  This is issue #71

**Comment by epitron** [comment]
The error messages are being swalloed with `rake build_lib` and `gem install` as well...

**Comment by krim** [comment]
Have the save issue on Ubuntu 14.04.
I resolve the problem by execute: "cargo build --release" from gem dir, such as: "bundle/ruby/2.3.0/bundler/gems/faster_path-274f2329e9be"

**Comment by danielpclark** [comment]
Hopefully this commit https://github.com/danielpclark/faster_path/commit/69ea7df970c7bc7dc1d2dae45004fb95051c8fdc should have fixed this issue.

**Comment by danielpclark** [comment]
I've written an AssetResolution module that will build the library on require if it wasn't built during gem install.  If that fails it will error out with a very clear message as to why.  This specifically makes sure the library is where expected in the gem's directory.

The upcoming Thermite PR should also handle the location of the library appropriately.
