### ISSUE TITLE
Bundler extension refactor

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/faster_path#71]
The current Bundler `extconf.rb` implementation has it's rake command error messages swallowed up by the Bundler gem installation system.  We need to refactor the extension building to be verbose through Bundler.

Also a way to test a bundle install of the gem in the test suite would be nice.

**Comment by danielpclark** [comment]
This will help with #18, #20, and #68.

**Comment by malept** [comment]
Have you considered, instead of using `extconf.rb`, doing:

```ruby
spec.extensions << 'ext/Rakefile'
```

which would have as its default something that looks like `build_lib` in your root `Rakefile`.

That's the approach I'm taking for the extensions I'm building with my [thermite](https://github.com/malept/thermite) Rake tasks.

**Comment by danielpclark** [comment]
Thank you! @malept 

I wasn't able to find documentation for using the Rakefile alternative to Makefile.  But I did see some code in Bundler that would use something like it as an alternative.

I'd like to try it out but I will need people with other operating systems to test it out as well.

**Comment by travisofthenorth** [comment]
Not sure if this is helpful, but the same issue is present when you simply run `gem install faster_path`.

**Comment by danielpclark** [comment]
@travisofthenorth That does give us a bit more information to work with.  It still leaves a lot of unknowns.

**Comment by malept** [comment]
I'm currently in the middle of figuring out building on Windows, but when I've got that working reasonably (and actually releasing a gem), I'd like to take a crack at integrating thermite with faster_path.

**Comment by danielpclark** [comment]
@malept Maybe you have some input on whether you'd like to see the current implementation changed for type errors? #74 Otherwise I'd your version to `0.1.8` for the time being.

**Comment by malept** [comment]
Sure, I'll try to take a look later tonight.

**Comment by danielpclark** [comment]
Putting notes here for later.

* Rakefile extension installs: https://github.com/rake-compiler/rake-compiler
* Getting gemspec: http://stackoverflow.com/a/34704531/1500195
* RubyGems has RakeBuilder (Bundler does not): https://github.com/rubygems/rubygems/blob/master/lib/rubygems/ext/rake_builder.rb
* Bundler's gem installer: https://github.com/bundler/bundler/blob/master/lib/bundler/installer/gem_installer.rb

Note: Ruby has a tendancy to like to put libraries in both the gem's lib directory and a platform specific gem directory:

```
./gems/ruby-2.3.1/gems/ffi-1.9.10/lib/ffi_c.so
./gems/ruby-2.3.1/gems/ffi-1.9.10/ext/ffi_c/ffi_c.so
```
Which is supportive of jRuby.

And the platform specific:

```
./gems/ruby-2.3.1/extensions/x86_64-linux/2.3.0/ffi-1.9.10/ffi_c.so
```

Perhaps we could consider using a standardized ruby path to link the gem.  Before that though we would need to place the linked library in each of these locations. Just a thought.
