### ISSUE TITLE
FasterPath.dirname from already implemented Rust version

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/faster_path#8]
The Rust code has already been written for `dirname` .

Details:
* The method needs to be added in `FasterPath`
* The refinement needs to be created for `File` which means creating a new refinement called `RefineFile`
* Add the monkeypatch of the `File` class to the `sledgehammer_everything!` method
* Write tests showing it works
* Write tests to prove the behavior is the same as the existing `File.dirname`
* Write benchmarks for comparing `File.dirname` to `FasterPath.dirname` and update the `README.md` with the percentage of improvement

**Comment by gogainda** [comment]
I could take that

**Comment by gogainda** [comment]
https://github.com/danielpclark/faster_path/pull/13

**Comment by danielpclark** [comment]
Looks really good!

We should not handle `:to_path` in `FasterPath.dirname` .  The FasterPath implementation should be pure Rust so no need to type check here.  We want people to have the option of running pure Ruby methods which is what FasterPath provides on itself, whereas the refinements and monkey patches should be the same.

In the refinement and monkey patch of File.dirname there you can handle the `:to_path` scenario and type checking.

Now as for the tests.

The trailing slash is intentional behavior for FasterPath
```
assert_equal('/home', FasterPath.dirname('/home/jason'))#failing
assert_equal('/foo', FasterPath.dirname('/foo/bar/'))#failing
```

This scenario was not accounted for so it should be fixed in Rust
```
assert_equal(".", FasterPath.dirname("foo"))#failing
assert_equal(".", FasterPath.dirname(""))#failing
```

**Comment by danielpclark** [comment]
The reason the trailing slash is expected behavior in FasterPath is it is way too common to join strings with an additional call to the operating systems separator.  Also having a double slash in the OS path will not break anything.

So instead of getting `/home` and doing `dir + SEP + file` people can now skip adding in the separator.  It's more efficient and won't break anything.

**Comment by danielpclark** [comment]
I believe I'll need to have two copies of this method in Rust since I'm currently using one for `chop_basename` and changing this method will cause a side effect for that.

**Comment by gogainda** [comment]
Shold I copy past the rust implementation for dirname and fix it?

**Comment by danielpclark** [comment]
Yes.  But I recommend renaming the one for `chop_basename` to `dirname_for_chop`.  And that can be replaced inside `FasterPath.chop_basename` to call `Rust.dirname_for_chop`.  Once the `FasterPath.chop_basename` is decoupled you may fix the Rust implementation of `basename`.

**Comment by danielpclark** [comment]
Would you like me to rename a copy to `dirname_for_chop`?

**Comment by danielpclark** [comment]
Actually I've changed my mind on the trailing slash.  We'll maintain the same behavior.  Reason is I forgot how people like to use parts dynamically and may use file/directory names as constants.  So this would be breaking behavior.  I'll be removing the trailing slash from the implementation myself.

**Comment by gogainda** [comment]
Yes, this would be useful

**Comment by danielpclark** [comment]
Alright.  I've thought more about dirname having a trailing slash.  It's too risky to allow different behavior for monkey-patched methods.  I'll try and write my own chomp method for the trailing character and see if it's faster than using Ruby's.

**Comment by danielpclark** [comment]
The methods are decoupled. https://github.com/danielpclark/faster_path/pull/21

**Comment by danielpclark** [comment]
Feel free to ask anything of me on this.  If you want me to take the work here and rewrite the Rust to pass the tests I'll consider this done for you.  It's up to you :smiley:

**Comment by gogainda** [comment]
I think next Monday I will decide whether I continue this work or pass it over to you. Right now I kind of stuck with Rust implementation, especially for edge cases like 
```
"./b/./"
```
when I asking for parent rust returns me '/' which is not what I expected. For now I don't know better solution that remove from incoming path all '/./' .What do you think?

**Comment by danielpclark** [comment]
Rust has a very hands off approach to paths.  Especially when dealing with `..`  It might be more expedient to write it from scratch.  I don't know.

**Comment by danielpclark** [comment]
Have a look at the new [basename](https://github.com/danielpclark/faster_path/blob/master/src/basename.rs) implementation.  To get faster performance I had to avoid regex and paths.

**Comment by danielpclark** [comment]
Let me know when you decide about writing the Rust code or not.  I'm fine with whatever. :+1:

**Comment by danielpclark** [comment]
I fixed what was broken in `chop_basename` compatibility.  For that Ihad to change my `dirname_for_chop` method.  It no longer uses Rust's path.  And it may work for you as well. [dirname_for_chop](https://github.com/danielpclark/faster_path/blob/master/src/dirname_for_chop.rs)

**Comment by gogainda** [comment]
thanks, will look into it

**Comment by danielpclark** [comment]
Hey, I just thought of this.  But can you also add `using FasterPath::RefineFile` In each of the class objects in the `test/ripple_effect` folder?  Just add it to the `RefinedParhname` class and that'll work.

**Comment by gogainda** [comment]
What about bad performance, could you suggest a way to make the implementation work faster?

**Comment by danielpclark** [comment]
Yes, if it all possible remove all type safety checking in the Ruby code.  Also I've found Rubys standard library is written stupidly simple for efficiency.  So the way you've written your code is too smart.  Find the dumbest simple way to make it pass the same tests.  For example the glob check in the `basename` method totally fakes it.

I had to rewrite `basename` 3 times before I got it to be more efficient than Ruby.  You can look at the git history of my two smart implementations that were 60x and 5600x slower.

**Comment by danielpclark** [comment]
Less Ruby code means more performance.

**Comment by gogainda** [comment]
Yeah, I know, but I dont use ruby in FasterPath.dirname implementation, it is just wrapper around rust implementation, so the last thing I can do is invent some dead simple solution for dirname implementation

**Comment by danielpclark** [comment]
I know I had mentioned before about having the type checking moved out of FasterPath module and into the refinements.  But if we do that our benchmarks will be inaccurate.  I believe FFI itself is enough to type check the string and it may even work well without to_path as it may ensure proper string enforcement.

**Comment by gogainda** [comment]
Updated the PR and made some measurements. 
Turns out that even if I have rust implementation that returns a dot:
```
return CString::new(".").unwrap().into_raw();
``` 
it already has the same performance as File.dirname. My guess is that there is no way to make it faster than C implementation.

**Comment by danielpclark** [comment]
I'll look into this myself to confirm.
