### ISSUE TITLE
Need more accurate benchmarks (discussion)

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/faster_path#86]
The `pbench` tests (which are how we measure) can fluctuate too much.  I've set the repetitions to be done in the same quantity just to get more stable results.  But even so there is fluctuation.

I'm considering the possibility of writing a Rust Minitest plugin that creates time stamps from Rust and measures in microseconds rather than seconds.  One of the new tools being worked on that may help in regression checks only looks at the verbose test output for how many seconds have changed.  If we build this as Minitest Reporter we can convert all time output to microseconds.

Also I think Rust may get more accurate time foot prints but we need to dance around Ruby's GC.

**Comment by glebm** [comment]
Here are some ideas:

1. Run GC out-of-band, i.e.:
  1. Disable GC.
  2. Run and measure iteration.
  3. Run GC if (i + 1) % 1000 == 0.
2. Instead of running a fixed number of iterations, run them until total iterations time is at least 1 second for the baseline. Then run the same number of iterations for the faster_path version.

**Comment by danielpclark** [comment]
> run them until total iterations time is at least 1 second for the baseline

Great idea.  We should try [benchmark-ips](https://github.com/evanphx/benchmark-ips) first.

> Run GC if (i + 1) % 1000 == 0.

I'm not sure I follow.  But disabling GC for a benchmark sounds like a good idea.

**Comment by glebm** [comment]
> > Run GC if (i + 1) % 1000 == 0.

> I'm not sure I follow. But disabling GC for a benchmark sounds like a good idea.

Disable GC, only run it every 1000 iterations outside of the measurements to avoid OOM.

**Comment by danielpclark** [comment]
The benchmark-ips Github README shows a disable GC example for implementation. :smiley:

**Comment by glebm** [comment]
benchmark-ips looks good and the implementation is probably solid because Evan Phoenix. :smile:

**Comment by danielpclark** [comment]
Would you be interested in converting existing benchmarks over as a PR?

**Comment by danielpclark** [comment]
I'll take it that you would consider that a chore and are therefor not interested.  I'll add this to my list of TODOs.

**Comment by danielpclark** [comment]
I've written Visual benchmarks for this https://github.com/danielpclark/faster_path/pull/97
