### ISSUE TITLE
back compatibility class and method | monkeypatch everything everywhere

### ISSUE THREAD

**Issue by mibamur** [danielpclark/faster_path#87]
Hello!

### You say
> If you want to see the best results in Rails with this gem you will likely need to be using the Sprockets 2.0 series. Otherwise this library would need to rewrite Sprockets itself.

> And for the sledgehammer of monkey patching you can do

Can I use it for all rubies call, bundler, gem and so on?

```rb
require "faster_path/optional/monkeypatches"
FasterPath.sledgehammer_everything!
```

I should past it every where?

**Comment by danielpclark** [comment]
You don't need to paste it everywhere.

If you have a Gemfile with `gem 'faster_path'` in it you can create a file in a Rails project at `config/initializers/faster_path.rb` and put:

```
require "faster_path/optional/monkeypatches"
FasterPath.sledgehammer_everything!
```
in it.

If you are not making a Rails project you can just put it in one place where your application starts up.

**Comment by mibamur** [comment]
@danielpclark thanks

I put it there, as I understand it is first file that "rails" (or Rack) load
```rb
# config.ru
require "faster_path/optional/monkeypatches"
FasterPath.sledgehammer_everything!
# This file is used by Rack-based servers to start the application.

require_relative 'config/environment'
run Rails.application
```

Question:
Can I use it with "default" other rubies gems like `bundle`, `gem`, `rake`, not only Rails or other projects?

So rvm before run anithing rubies run some hook, I think I should inject it there are
Can it be answer for my question? :-)

**Comment by danielpclark** [comment]
> Can I use it with "default" other rubies gems like bundle, gem, rake, not only Rails or other projects?

Yes

> So rvm before run anithing rubies run some hook, I think I should inject it there are

The monkey-patch effect all of the current running program.  You're more than welcome to try it in any other gem or project.  You might consider using the refinements though if you want to narrow down where it gets changed.

```ruby
Thing.using FasterPath::RefinePathname
```

That way only what's run in `Thing` will use the new methods and not the others.

**Comment by mibamur** [comment]
thanks a lot
PS
gem is great
