### ISSUE TITLE
Automatic rust install?

### ISSUE THREAD

**Issue by NullVoxPopuli** [danielpclark/faster_path#89]
Not sure if you want to do this,
This is kinda controversial, but I've done this: https://github.com/NullVoxPopuli/case_transform-rust-extensions/blob/master/ext/case_transform/build.sh

Which basically automatically downloads and sets up rust and cargo.

It's tough, cause C tools already come with every dev environment, so it's hard to achieve that same usability upon install.

**Comment by malept** [comment]
I would argue that https://github.com/danielpclark/faster_path/pull/88 accomplishes this in a different way, by installing pre-compiled Rust extensions.

**Comment by NullVoxPopuli** [comment]
huh -- maybe I just haven't fully checkout out thermite's options.

**Comment by malept** [comment]
Let me know if there's places in Thermite's documentation that needs improvement.

**Comment by NullVoxPopuli** [comment]
@malept I posted an issue on the thermite repo regarding this issue

**Comment by danielpclark** [comment]
@NullVoxPopuli I do like the idea.  But I think the Rust install should be a gem built just for that purpose.  A wrapper install script gem.  Then I could have this project depend on that if it that ends up being a better solution.

Currently I've been working hard on trying to test gem bundling so I can verify when I get forced rust extension compiling to work.  A couple other issues are open for people not getting the extension to compile when Bundler does a gem install.  I can neither prove or deny the issue in a test so it's my primary focus at the moment.

**Comment by danielpclark** [comment]
Unless Rust is entirely encapsulated with a gem, I don't see this as a viable solution.  For now I'm going the Thermite way and may revisit such ideas like this later.
