### ISSUE TITLE
JRuby has some limitations & not install

### ISSUE THREAD

**Issue by sinankeskin** [danielpclark/faster_path#9]
I tried your gem with JRuby just for fun and and i saw some limitations.

First of all you can't compile C extension (obviously) with JRuby. That's why `mkmf.rb` has only one line which is

``` ruby
raise NotImplementedError, "C extensions are not supported"
```

Because of that i think you should change your `extconf.rb`. You can't use `find_executable` etc.

In my personal opinion you don't have to create dummy makefile either (since you don't have C extension). Simply, keep only rake tasks in this file and also i think created library files should be in `lib` folders. Not necessary but best practice i guess??? `Ex: Nokogiri`

FFI has Java version therefore i assume all others works ok. This version doesn't install as is.

**Comment by danielpclark** [comment]
@sinankeskin The reason I wrote `extconf.rb` is for the bundle gem system to trigger the install.  It was the only way I found to hook executing Ruby code on gem installations from a Gemfile.  Do you know of another way?

**Comment by sinankeskin** [comment]
No, I mean keep the ``extconf.rb`` but clear the all other lines. Only keep this block.
```ruby
Dir.chdir('../../') do
  `rake build_src`
  `rake clean_src`
end
```
You can check whether cargo is installed or not with single back tick like:

```ruby
puts `cargo --version`
```

It returns ``cargo 0.10.0-nightly (10ddd7d 2016-04-08)`` for me.

**Comment by danielpclark** [comment]
I'll check it out.  If cargo isn't installed it raises `Errno::ENOENT` so that can be handled easily with `rescue nil`

**Comment by danielpclark** [comment]
I'm letting Travis compile it now https://github.com/danielpclark/faster_path/tree/jruby_support

**Comment by danielpclark** [comment]
Had to revert jRuby support as bundle would fail in Rails without a Makefile. https://github.com/danielpclark/faster_path/commit/d97efc44e78a63172d92b6e615074ab8461e27cc

If we want to fix this we will need to deal with needing the Makefile to exist.

**Comment by danielpclark** [comment]
Thermite https://github.com/danielpclark/faster_path/pull/88 may resolve most of the issues working with jRuby providing an appropriate binary is available.
